name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build and Test
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: fwal/setup-swift@v1
        with:
          swift-version: 5.9
      - name: Build
        run: swift build
      - name: Test
        run: swift test
